let EVENTS=[];
fetch('data/events.json').then(r=>r.json()).then(data=>{EVENTS=data;initEvents()}).catch(()=>{EVENTS=[]});
function card(e){return `<article class="event-card"><button class="heart" onclick="toggleWish('${e.id}',this)">♡</button><div class="event-image ${e.imageClass}"><div class="date"><b>${e.day}</b>${e.month}</div></div><div class="event-body"><span class="event-tag">${e.category}</span><h3>${e.name}</h3><div class="event-meta"><span>◷ ${e.time}</span><span>⌖ ${e.city}</span></div><p class="muted">${e.description}</p><div class="event-price"><strong>From ₹${e.price.toLocaleString('en-IN')}</strong><a class="btn btn-primary small" href="event-details.html?id=${e.id}">View event</a></div></div></article>`}
function initEvents(){
 const params=new URLSearchParams(location.search); const search=params.get('search')||''; const cat=params.get('category')||'';
 const input=$('#searchInput'), cf=$('#categoryFilter');
 if(input) input.value=search; if(cf&&cat) cf.value=cat;
 if($('#eventList')) renderList();
 if($('#featuredEvents')) $('#featuredEvents').innerHTML=EVENTS.filter(e=>e.featured).map(card).join('');
 if($('#details')) renderDetails(params.get('id')||EVENTS[0]?.id);
 if($('#wishlistList')) renderWishlist();
}
function renderList(){const q=($('#searchInput')?.value||'').toLowerCase(),cat=$('#categoryFilter')?.value||'',type=$('#typeFilter')?.value||'',price=Number($('#priceFilter')?.value||0);let list=EVENTS.filter(e=>(!q||e.name.toLowerCase().includes(q)||e.description.toLowerCase().includes(q))&&(!cat||e.category===cat)&&(!type||e.type===type)&&(!price||e.price<=price));$('#eventList').innerHTML=list.length?list.map(card).join(''):'<div class="no-results"><h2>No events found</h2><p>Try changing your search or filters.</p></div>';$('#resultCount').textContent=`Showing ${list.length} event${list.length!==1?'s':''}`;}
['searchInput','categoryFilter','typeFilter','priceFilter'].forEach(id=>document.getElementById(id)?.addEventListener('input',renderList));
function clearFilters(){['searchInput','categoryFilter','typeFilter','priceFilter'].forEach(id=>{const x=$('#'+id);if(x)x.value=''});renderList()}
function renderDetails(id){const e=EVENTS.find(x=>x.id===id)||EVENTS[0];if(!e)return;$('#details').innerHTML=`<section class="page-hero"><span class="eyebrow">${e.category.toUpperCase()} · ${e.type.toUpperCase()}</span><h1>${e.name}</h1><p>${e.description}</p></section><section class="section compact"><div class="booking-layout"><div><div class="event-image ${e.imageClass}" style="height:340px;border-radius:22px"><div class="date"><b>${e.day}</b>${e.month}</div></div><div class="form-card" style="margin-top:20px"><span class="eyebrow">ABOUT THE EVENT</span><h2>Experience something memorable.</h2><p>${e.description} Expect curated sessions, interactive moments and a welcoming community.</p><h3>Schedule</h3><p>10:00 AM — Registration & welcome<br>11:00 AM — Main session<br>01:00 PM — Interactive experience<br>03:00 PM — Networking<br>04:30 PM — Closing</p><h3>Organizer</h3><p><b>${e.organizer}</b><br>Event management & experience design team.</p><h3>Venue</h3><p>${e.venue}, ${e.city}</p></div></div><aside class="summary-card"><span class="eyebrow">TICKETS FROM</span><h2>₹${e.price.toLocaleString('en-IN')}</h2><p>Per ticket · taxes calculated at checkout</p><p>📅 ${e.date}<br>◷ ${e.time}<br>⌖ ${e.venue}</p><a class="btn btn-primary full" href="seats.html?event=${e.id}">Select seats →</a><a class="btn btn-outline full" style="margin-top:10px" href="booking.html?event=${e.id}">Quick booking</a></aside></div></section>`}
function toggleWish(id,btn){let w=JSON.parse(localStorage.getItem('eventnova-wishlist')||'[]');if(w.includes(id)){w=w.filter(x=>x!==id);btn.textContent='♡'}else{w.push(id);btn.textContent='♥'}localStorage.setItem('eventnova-wishlist',JSON.stringify(w))}
function renderWishlist(){let w=JSON.parse(localStorage.getItem('eventnova-wishlist')||'[]');let list=EVENTS.filter(e=>w.includes(e.id));$('#wishlistList').innerHTML=list.length?list.map(card).join(''):'<div class="no-results"><h2>Your wishlist is empty</h2><p>Save events you love and find them here later.</p><a class="btn btn-primary" href="events.html">Explore events</a></div>'}